#!/bin/bash

# Glitch kernel build-script (Dual Edition)	#
#					  	#
# Options :				  	#
#						#
# cm : build cm variant	if any		  	#
# clean : clean the build directory       	#
# cleank : clean the built kernel packages	#
# cleanc : clean the compiler cache		#
#################################################

# Device options :
	target_name="flo" #defines the device name/codename for config
	target_config=$target_name"_defconfig" #defines the device name/codename for config
	target_device="N7-2013" #defines the name of device-related folders (can be the same as $target_name)

# Toolchain selection :
# (default path is "kernel_tree_folder/../toolchains")
# -------linux-x86
	#export CROSS_PREFIX="Linaro-arm-eabi-5.2.0/bin/arm-eabi-"
	#export CROSS_PREFIX="gcc-linaro-5.3-2016.02-x86_64_arm-eabi/bin/arm-eabi-"
	export CROSS_PREFIX="gcc-linaro-6.3.1-2017.02-x86_64_arm-eabi/bin/arm-eabi-"
	#export CROSS_PREFIX="gcc-linaro-4.9-2016.02-x86_64_arm-eabi/bin/arm-eabi-"

# -------darwin-x86
	#export CROSS_PREFIX=""

setup ()
{

if [ ! -f arch/arm/configs/Glitch_$target_name"_defconfig" ] ; then
echo "Glitch defconfig missing. Creating one using original target defconfig. Use this one instead of default!"
echo "--------------------------------------------------------------------------------------------------------"
cp arch/arm/configs/$target_name"_defconfig" arch/arm/configs/Glitch_$target_name"_defconfig"
echo "done"
fi

function mka() {
    case `uname -s` in
        Darwin)
            make -j `sysctl hw.ncpu|cut -d" " -f2` "$@"
            ;;
        *)
            schedtool -B -n 1 -e ionice -n 1 make -j `cat /proc/cpuinfo | grep "^processor" | wc -l` "$@"
            ;;
    esac
};

#   Arch-dependent definitions
    case `uname -s` in
        Darwin)
            KERNEL_DIR="$(dirname "$(greadlink -f "$0")")"
            CROSS_PREFIX="$KERNEL_DIR/../toolchains/$CROSS_PREFIX"
            ;;
        *)
            KERNEL_DIR="$(dirname "$(readlink -f "$0")")"
            CROSS_PREFIX="$KERNEL_DIR/../toolchains/$CROSS_PREFIX"
            ;;
    esac

    BUILD_DIR="../glitch-build/kernel"

    if [ x = "x$NO_CCACHE" ] && ccache -V &>/dev/null ; then
        CCACHE=ccache
        CCACHE_BASEDIR="$KERNEL_DIR"
        CCACHE_COMPRESS=1
        CCACHE_DIR="$KERNEL_DIR/../.ccache"
        export CCACHE_DIR CCACHE_COMPRESS CCACHE_BASEDIR
    else
        CCACHE=""
    fi
}

build ()
{

    if [ "$type" = cm ] ; then
    target_variant="-CM" #defines the flashable zip additional name (CM)
    target_defconfig="Glitch_CM_$target_config" #defines the config to use for the build (CM)
    else
    target_variant="" #defines the flashable zip additional name
    target_defconfig="Glitch_$target_config" #defines the config to use for the build
    fi

    export ARCH="arm"
    local target=$target_device
    echo "-----------------------------------------"
    if [ "$type" = cm ] ; then
    echo "Building for $target_device CM using $target_defconfig"
    else
    echo "Building for $target_device AOSP using $target_defconfig"
    fi
    local target_dir="$BUILD_DIR/$target_device"
    local module
    rm -fr "$target_dir"
    rm -f $KERNEL_DIR/tmp_$target_defconfig
    rm -f $KERNEL_DIR/arch/arm/configs/release_$target_defconfig
    mkdir -p "$target_dir"

. $KERNEL_DIR/../rev

if [ "$type" = cm ] ; then
echo "Using same version number as regular build"
else
counter=$((counter + 1))
fi

echo "-----------------------------------------"
echo "Write release number in config (r"$counter")"

if [ "$type" = cm ] ; then
releasenumber='CONFIG_LOCALVERSION="-Glitch-N7-CM-r'$counter'-N"'
else
releasenumber='CONFIG_LOCALVERSION="-Glitch-N7-AOSP-r'$counter'-N"'
fi

cp arch/arm/configs/$target_defconfig tmp_$target_defconfig;
sed "43s/.*/$releasenumber/g" tmp_$target_defconfig > release_$target_defconfig;
mv release_$target_defconfig arch/arm/configs/release_$target_defconfig
rm -f $KERNEL_DIR/tmp_$target_defconfig

    mka -C "$KERNEL_DIR" O="$target_dir" release_$target_defconfig HOSTCC="$CCACHE gcc"
    mka -C "$KERNEL_DIR" O="$target_dir" HOSTCC="$CCACHE gcc" CROSS_COMPILE="$CCACHE $CROSS_PREFIX" zImage

[[ -d release ]] || {
	echo "-----------------------------------------"
	echo "must be in kernel root dir"
	exit 1;
}

echo "-----------------------------------------"

#echo "copying modules and zImage"

#Aroma
#mkdir -p $KERNEL_DIR/release/aroma/system/lib/modules/
#Restore
#mkdir -p $KERNEL_DIR/release/restore/system/lib/modules/

#cd $target_dir

#Aroma
#find -name '*.ko' -exec cp -av {} $KERNEL_DIR/release/aroma/system/lib/modules/ \;
#"$CROSS_PREFIX"strip --strip-unneeded $KERNEL_DIR/release/aroma/system/lib/modules/*
#Restore
#find -name '*.ko' -exec cp -av {} $KERNEL_DIR/release/restore/system/lib/modules/ \;
#"$CROSS_PREFIX"strip --strip-unneeded $KERNEL_DIR/release/restore/system/lib/modules/*

echo "Copying files and folders to packaging destination,"

cd $KERNEL_DIR
rm -f arch/arm/configs/release_$target_defconfig

#Aroma
mkdir -p $KERNEL_DIR/release/build/aroma
cp -r $KERNEL_DIR/release/build/magic $KERNEL_DIR/release/build/aroma/magic
cp $target_dir/arch/arm/boot/zImage $KERNEL_DIR/release/build/aroma/magic/glitch.zImage
cp -r $KERNEL_DIR/release/build/META-INF-aroma $KERNEL_DIR/release/build/aroma/META-INF
cp -r $KERNEL_DIR/release/build/system $KERNEL_DIR/release/build/aroma/system

#Restore
mkdir -p $KERNEL_DIR/release/build/restore
cp -r $KERNEL_DIR/release/build/magic $KERNEL_DIR/release/build/restore/magic
cp $target_dir/arch/arm/boot/zImage $KERNEL_DIR/release/build/restore/magic/glitch.zImage
cp -r $KERNEL_DIR/release/build/META-INF-restore $KERNEL_DIR/release/build/restore/META-INF
cp -r $KERNEL_DIR/release/build/system $KERNEL_DIR/release/build/restore/system

echo "Setting date & version in Aroma conf ("$(date +%B)" "$(date +%e)" "$(date +%Y)"),"

if [ "$type" = cm ] ; then
AromaVersionReplace='ini_set("rom_version",          "N7-CM");'
else
AromaVersionReplace='ini_set("rom_version",          "N7-AOSP");'
fi

AromaDateReplace='ini_set("rom_date",             "'$(date +%B)' '$(date +%e)' '$(date +%Y)'");'

sed "34s/.*/$AromaVersionReplace/g" ./release/build/aroma/META-INF/com/google/android/aroma-config > ./aroma-config.tmp;
mv ./aroma-config.tmp ./release/build/aroma/META-INF/com/google/android/aroma-config
sed "37s/.*/$AromaDateReplace/g" ./release/build/aroma/META-INF/com/google/android/aroma-config > ./aroma-config.tmp;
mv ./aroma-config.tmp ./release/build/aroma/META-INF/com/google/android/aroma-config

echo "Packaging it up,"

mkdir -p $KERNEL_DIR/release/$target_device-out

#Aroma
cd $KERNEL_DIR/release/build/aroma
REL=Glitch-N.$target_name.r$counter$target_variant-Full.zip

	zip -q -r ${REL} magic META-INF system
	#sha256sum ${REL} > ${REL}.sha256sum
	mv ${REL}* $KERNEL_DIR/release/$target_device-out/

#Restore
cd $KERNEL_DIR/release/build/restore
REL2=Glitch-N.$target_name.r$counter$target_variant-Pure.zip

	zip -q -r ${REL2} magic META-INF system
	#sha256sum ${REL2} > ${REL2}.sha256sum
	mv ${REL2}* $KERNEL_DIR/release/$target_device-out/

rm -fr $KERNEL_DIR/release/build/aroma
rm -fr $KERNEL_DIR/release/build/restore

if [ "$type" = cm ] ; then
echo "Using same version number as regular build."
else
echo counter=$counter > $KERNEL_DIR/../rev;
fi

echo "-----------------------------------------"
echo "Aroma   : "${REL}
echo "Restore : "${REL2}
}
    
setup

if [ "$1" = clean ] ; then
    rm -fr "$BUILD_DIR"/*
    cd release
    rm `find ./ -name '*.*~'` -rf
    rm `find ./ -name '*~'` -rf
    cd $KERNEL_DIR
    rm -f $KERNEL_DIR/tmp_$target_defconfig
    rm -f arch/arm/configs/release_$target_defconfig
    rm -f $KERNEL_DIR/tmp_$target_defconfig
    rm -f $KERNEL_DIR/arch/arm/configs/release_$target_defconfig
    echo "-----------------------------------"
    echo "Build folder and temp files cleaned"
    echo "-----------------------------------"

else

if [ "$1" = cleank ] ; then
    rm -fr "$KERNEL_DIR"/release/$target_device-out/*
    echo "---------------------"
    echo "Built kernels cleaned"
    echo "---------------------"

else

if [ "$1" = cleanc ] ; then
    rm -rf ../.ccache
    echo "----------------------"
    echo "Compiler cache cleaned"
    echo "----------------------"

else

time {

if [ "$1" = cm ] ; then
if [ -f arch/arm/configs/Glitch_CM_$target_name"_defconfig" ] ; then
export type="cm"
else
echo "No CM-specific defconfig found. Try without cm. Who needs cm anyway if it's AOSP compatible?"
fi
else
export type="regular"
fi

    build $target_device

}
fi
fi
fi
